---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/categories":
    get:
      summary: list categories
      responses:
        '200':
          description: successful
  "/api/v1/categories/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show category and relationated products
      responses:
        '200':
          description: successful
  "/api/v1/products/page/{page}":
    parameters:
    - name: page
      in: path
      description: page
      required: true
      schema:
        type: string
    get:
      summary: paginate product
      responses:
        '200':
          description: successful
  "/api/v1/products":
    get:
      summary: list products
      responses:
        '200':
          description: successful
  "/api/v1/searchs?query={params}":
    parameters:
    - name: params
      in: path
      description: parameter
      required: true
      schema:
        type: string
    get:
      summary: list searches products
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
